-- ══════════════════════════════════════════════════════════════════════
-- fix-phase26-library-content.sql — Spice, tool, cut, preservation starters
-- Safe to re-run. Run after fix-phase25-library-starter.sql
-- ══════════════════════════════════════════════════════════════════════

INSERT INTO public.spice_profiles (slug, name, also_known_as, heat_level, flavour_wheel, how_to_toast, when_to_add, chefs_notes, did_you_know, status, visibility) VALUES
('cumin', 'Cumin', 'Jeera, comino', 1, 'Warm, earthy, slightly bitter — backbone of many spice blends.', 'Toast whole seeds in a dry pan 30–60 seconds until fragrant; grind fresh for maximum impact.', 'Add ground cumin early in oil for depth; whole seeds in tempering (tadka) at the end.', 'Buy whole seeds if you can — pre-ground loses aroma quickly.', 'Cumin appears in archaeological sites in Syria dating to the second millennium BCE.', 'published', 'public'),
('turmeric', 'Turmeric', 'Haldi, curcuma', 0, 'Earthy, slightly bitter, vivid golden colour — more colour than heat.', 'Usually used ground; no toasting needed. Bloom briefly in fat to reduce raw edge.', 'Add early with onion/garlic base; stains everything — use a dedicated board.', 'Pair with black pepper — piperine helps absorption of curcumin.', 'Fresh turmeric root stains hands for days; dried powder is the everyday form.', 'published', 'public'),
('black-pepper', 'Black Pepper', 'Peppercorns', 2, 'Pungent, piney heat — sharp rather than chilli heat.', 'Toast lightly; crack or grind just before use.', 'Finish delicate sauces with cracked pepper; add ground early in stocks.', 'Tellicherry and Malabar are prized origins — but freshness matters more than label.', 'Black pepper was once so valuable it was used as currency in some trade routes.', 'published', 'public')
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, also_known_as=EXCLUDED.also_known_as, heat_level=EXCLUDED.heat_level,
  flavour_wheel=EXCLUDED.flavour_wheel, how_to_toast=EXCLUDED.how_to_toast, when_to_add=EXCLUDED.when_to_add,
  chefs_notes=EXCLUDED.chefs_notes, did_you_know=EXCLUDED.did_you_know, status=EXCLUDED.status, visibility=EXCLUDED.visibility, updated_at=now();

INSERT INTO public.tool_profiles (slug, name, tool_category, what_its_for, how_to_use, how_to_care, chefs_notes, did_you_know, status, visibility) VALUES
('cast-iron-skillet', 'Cast Iron Skillet', 'Cookware', 'Searing, frying, baking, stove-to-oven dishes — unmatched heat retention.', 'Preheat gradually; use enough fat; avoid acidic simmered sauces for hours (can affect seasoning early on).', 'Clean while warm; dry thoroughly; thin oil wipe after washing. Re-season if food sticks.', 'A well-used skillet beats a new non-stick for steak and cornbread.', 'Cast iron has been used for cooking for over two thousand years.', 'published', 'public'),
('chefs-knife', 'Chef''s Knife', 'Knives', 'General prep — chop, slice, rock-mince herbs, break down vegetables.', 'Pinch grip on blade; curl fingers on guide hand; let the knife do the work — don''t saw aggressively.', 'Hone regularly; professional sharpen yearly. Hand-wash; no dishwasher for wooden handles.', 'An 20–25 cm (8–10 inch) chef''s knife suits most home cooks.', 'The French chef''s knife profile became standard in professional kitchens in the 19th century.', 'published', 'public'),
('digital-kitchen-scale', 'Digital Kitchen Scale', 'Measuring', 'Baking accuracy, coffee, portioning, reducing washing-up from multiple cups.', 'Zero (tare) with bowl on scale; weigh liquids in grams for consistency.', 'Wipe clean; avoid submerging display unit; replace batteries when readings drift.', 'Grams beat cups for repeatability — especially baking and spice blends.', 'Professional kitchens weigh almost everything; home cooks gain consistency the same way.', 'published', 'public')
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, tool_category=EXCLUDED.tool_category, what_its_for=EXCLUDED.what_its_for,
  how_to_use=EXCLUDED.how_to_use, how_to_care=EXCLUDED.how_to_care, chefs_notes=EXCLUDED.chefs_notes,
  did_you_know=EXCLUDED.did_you_know, status=EXCLUDED.status, visibility=EXCLUDED.visibility, updated_at=now();

INSERT INTO public.cut_profiles (slug, name, protein_type, characteristics, how_to_prep, best_cooking_methods, chefs_notes, did_you_know, status, visibility) VALUES
('chicken-thigh', 'Chicken Thigh', 'chicken', 'More fat and connective tissue than breast — forgiving, flavourful, harder to dry out.', 'Trim excess skin flap if desired; pat dry for crisp skin; bone-in or boneless both work.', 'Roast skin-up, braise, grill, curry — suits longer gentle heat.', 'Default choice for many home cooks when breast dries out.', 'Dark meat contains more myoglobin — that is why it stays juicier.', 'published', 'public'),
('salmon-fillet', 'Salmon Fillet', 'fish', 'Rich, oily fish — cooks quickly; skin can crisp beautifully.', 'Remove pin bones with tweezers; score skin lightly for even curl; pat very dry before searing.', 'Pan-sear skin-down, oven-finish, poach gently, cure for gravlax.', 'Wild vs farmed varies in fat and colour — both work when fresh.', 'Salmon is anadromous — born in freshwater, lives in the sea, returns to spawn.', 'published', 'public'),
('beef-mince', 'Beef Mince', 'beef', 'Versatile grind — fat percentage drives flavour and shrinkage.', 'Bring to room temp for burgers; don''t overwork patties; season just before cooking.', 'Bolognese, burgers, meatballs, tacos — brown well for depth.', '80/20 (or similar) fat ratio balances flavour and structure for burgers.', 'Mince texture changes with grind plate size — coarse for burgers, fine for sausages.', 'published', 'public')
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, protein_type=EXCLUDED.protein_type, characteristics=EXCLUDED.characteristics,
  how_to_prep=EXCLUDED.how_to_prep, best_cooking_methods=EXCLUDED.best_cooking_methods, chefs_notes=EXCLUDED.chefs_notes,
  did_you_know=EXCLUDED.did_you_know, status=EXCLUDED.status, visibility=EXCLUDED.visibility, updated_at=now();

INSERT INTO public.preservation_profiles (slug, name, technique_type, what_it_is, best_for, safety_notes, shelf_life, chefs_notes, did_you_know, status, visibility) VALUES
('quick-pickling', 'Quick Pickling (Refrigerator)', 'pickling', 'Fast vinegar brine — not shelf-stable canning; ready in hours to days.', 'Onions, cucumbers, carrots, chillies — bright acidity for salads and bowls.', 'Refrigerate always; consume within 2–3 weeks; not a substitute for proper canning.', '2–3 weeks refrigerated', 'Heat vinegar with salt/sugar; pour over veg while warm; cool then fridge.', 'Quick pickles are a restaurant staple for brightness — not the same as fermented pickles.', 'published', 'public'),
('freezing-leftovers', 'Freezing Cooked Food', 'freezing', 'Safe pause button for cooked dishes and components — quality varies by dish.', 'Curries, soups, stews, bread, blanched veg — less ideal for crisp fried food.', 'Cool quickly; shallow containers; label with date; thaw in fridge not counter.', '1–3 months typical quality window; longer safe but flavour fades', 'Freeze flat in bags to stack; leave headspace for liquids expanding.', 'Freezing stops microbial growth but does not destroy toxins already present.', 'published', 'public'),
('water-bath-canning', 'Water Bath Canning', 'canning', 'High-acid preserving in sealed jars — jams, pickles, tomatoes with added acid.', 'Fruit jams, chutneys, acidified tomato products — follow tested recipes.', 'CRITICAL: use tested recipes; check headspace; process time by jar size; discard if seal fails.', '12–18 months pantry if seal intact', 'Never improvise ratios for low-acid veg — botulism risk is real.', 'Home canning surged in popularity during the 2020s — safety education matters more than ever.', 'published', 'public')
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, technique_type=EXCLUDED.technique_type, what_it_is=EXCLUDED.what_it_is,
  best_for=EXCLUDED.best_for, safety_notes=EXCLUDED.safety_notes, shelf_life=EXCLUDED.shelf_life,
  chefs_notes=EXCLUDED.chefs_notes, did_you_know=EXCLUDED.did_you_know, status=EXCLUDED.status, visibility=EXCLUDED.visibility, updated_at=now();

SELECT 'spice' AS type, slug, name, status FROM public.spice_profiles WHERE slug IN ('cumin','turmeric','black-pepper')
UNION ALL SELECT 'tool', slug, name, status FROM public.tool_profiles WHERE slug IN ('cast-iron-skillet','chefs-knife','digital-kitchen-scale')
UNION ALL SELECT 'cut', slug, name, status FROM public.cut_profiles WHERE slug IN ('chicken-thigh','salmon-fillet','beef-mince')
UNION ALL SELECT 'preservation', slug, name, status FROM public.preservation_profiles WHERE slug IN ('quick-pickling','freezing-leftovers','water-bath-canning')
ORDER BY type, slug;
